// See https://aka.ms/new-console-template for more information

string A = "";
string B = "";
string C = "";
string D = "";
string E = "";
string F = "";
string G = "";
string H = "";
string I = "";
string J = "";
string K = "";
string L = "";
string M = "";
string N = "";
string O = "";
string P = "";
string Q = "";
string R = "";
string S = "";
string T = "";
string U = "";
string V = "";
string W = "";
string X = "";
string Y = "";
string Z = "";
string Å = "";
string Ä = "";
string Ö = "";
string A1 = "";
string B1 = "";
string C1 = "";
string D1 = "";
string E1 = "";
string F1 = "";
string G1 = "";
string H1 = "";
string I1 = "";
string J1 = "";
string K1 = "";
string L1 = "";
string M1 = "";
string N1 = "";
string O1 = "";
string P1 = "";
string Q1 = "";
string R1 = "";
string S1 = "";
string T1 = "";
string U1 = "";
string V1 = "";
string W1 = "";
string X1 = "";
string Y1 = "";
string Z1 = "";
string Å1 = "";
string Ä1 = "";
string Ö1 = "";
string Mellanrum = "";
string Utropstäcken = "";

bool a = true;
if (a = true)
{
    A = "a";
    A1 = "A";
}
bool b = true;
if (b = true)
{
    B = "b";
    B1 = "B";
}
bool c = true;
if (c = true)
{
    C = "c";
    C1 = "C";
}
bool d = true;
if (d = true)
{
    D = "d";
    D1 = "D";
}
bool e = true;
if (e = true)
{
    E = "e";
    E1 = "E";
}
bool f = true;
if (f = true)
{
    F = "f";
    F1 = "F";
}
bool g = true;
if (g = true)
{
    G = "g";
    G1 = "G";
}
bool h = true;
if (h = true)
{
    H = "h";
    H1 = "H";
}
bool i = true;
if (i = true)
{
    I = "i";
    I1 = "I";
}
bool j = true;
if (j = true)
{
    J = "j";
    J1 = "J";
}bool k = true;
if (k = true)
{
    K = "k";
    K1 = "K";
}
bool l = true;
if (l = true)
{
    L = "l";
    L1 = "L";
}
bool m = true;
if (m = true)
{
    M = "m";
    M1 = "M";
}
bool n = true;
if (n = true)
{
    N = "n";
    N1 = "N";
}bool o = true;
if (o = true)
{
    O = "o";
    O1 = "O";
}bool p = true;
if (p = true)
{
    P = "p";
    P1 = "P";
}bool q = true;
if (q = true)
{
    Q = "q";
    Q1 = "Q";
}bool r = true;
if (r = true)
{
    R = "r";
    R1 = "R";
}bool s = true;
if (s = true)
{
    S = "s";
    S1 = "S";
}bool t = true;
if (t = true)
{
    T = "t";
    T1 = "T";
}bool u = true;
if (u = true)
{
    U = "u";
    U1 = "U";
}bool v = true;
if (v = true)
{
    V = "v";
    V1 = "V";
}bool w = true;
if (w = true)
{
    W = "w";
    W1 = "W";
}bool x = true;
if (x = true)
{
    X = "x";
    X1 = "X";
}bool y = true;
if (y = true)
{
    Y = "y";
    Y1 = "Y";
}bool z = true;
if (z = true)
{
    Z = "z";
    Z1 = "Z";
}bool å = true;
if (å = true)
{
    Å = "å";
    Å1 = "Å";
}bool ä = true;
if (ä = true)
{
    Ä = "ä";
    Ä1 = "Ä";
}bool ö = true;
if (ö = true)
{
    Ö = "ö";
    Ö1 = "Ö";
}
bool mellanrum = true;
if (mellanrum = true)
{
    Mellanrum = " ";
}
bool utropstäcken = true;
if (utropstäcken = true)
{
    Utropstäcken = "!";
}
Console.WriteLine("Type hello world");   
string svar = Console.ReadLine();
while (svar == "hello world")
{
    

Console.WriteLine($"{A1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{B1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{C1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{D1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{E1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{F1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{G1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{A1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{B1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{C1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{D1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{A1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{B1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{C1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{D1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{E1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{F1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{G1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{H1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{I1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{J1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{K1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{A1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{B1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{C1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{D1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{E1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{F1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{G1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{H1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{I1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{J1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{K1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{A1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{B1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{C1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{D1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{E1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{F1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{G1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{H1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{I1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{J1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{K1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{L1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{M1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{N1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{A1}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{B1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{C1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{D1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{E1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{F1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{G1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{H1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{I1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{J1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{K1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{L1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{M1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{N1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{O1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{P1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Q1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{R1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{S1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{T1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{U1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{V1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{W1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{X1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Y1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Z1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Å1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Ä1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Ö1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{A1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{B1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{C1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{D1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{E1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{F1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{G1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{H1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{I1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{J1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{K1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{L1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{M1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{N1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{O1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{P1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{Q1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{R1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{S1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{T1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{U1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{V1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{A1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{B1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{C1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{D1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{E1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{F1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{G1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{H1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{I1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{J1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{K1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{L1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{M1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{N1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{A1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{B1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{C1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{D1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{E1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{F1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{G1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{H1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{I1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{J1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{K1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{L1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{M1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{N1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{O1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{P1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{Q1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{A1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{B1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{C1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{D1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{E1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{F1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{G1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{H1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{I1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{J1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{K1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{A1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{B1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{C1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{A1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{B1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{C1}");Thread.Sleep(25);
    Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{D1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{E1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{F1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{G1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{H1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{I1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{J1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{K1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{L1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{M1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{N1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{O1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{P1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Q1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{R1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{S1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{T1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{U1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{V1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{W1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{X1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Y1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Z1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Å1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Ä1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Ö1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{A1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{B1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{C1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{D1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{E1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{F1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{G1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{H1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{I1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{J1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{K1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{L1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{M1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{N1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{O1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{P1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Q1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{R1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{S1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{T1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{U1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{V1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{W1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{X1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Y1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Z1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Å1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Ä1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Ö1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}");Thread.Sleep(25);
    Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{A1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{B1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{C1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{D1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{E1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{F1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{G1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{H1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{I1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{J1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{K1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{L1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{M1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{N1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{O1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{P1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{Q1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{R1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{S1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{T1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{U1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{V1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{W1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{X1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{Y1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{Z1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{Å1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{Ä1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{Ö1}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H1}{E1}{L1}{L1}{O1}{Mellanrum}{W1}{O1}{R1}{L1}{D1}{Utropstäcken}{Utropstäcken}{Utropstäcken}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{A}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{B}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{C}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{D}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{E}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{F}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{G}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{A}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{B}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{C}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{D}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{A}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{B}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{C}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{D}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{E}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{F}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{G}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{H}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{I}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{J}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{K}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{A}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{B}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{C}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{D}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{E}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{F}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{G}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{H}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{I}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{J}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{K}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{A}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{B}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{C}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{D}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{E}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{F}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{G}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{H}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{I}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{J}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{K}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{L}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{M}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{N}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{A}");
Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{B}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{C}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{D}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{E}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{F}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{G}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{H}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{I}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{J}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{K}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{L}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{M}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{N}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{O}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{P}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Q}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{R}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{S}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{T}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{U}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{V}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{W}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{X}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Y}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Z}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Å}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Ä}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Ö}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{A}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{B}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{C}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{D}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{E}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{F}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{G}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{H}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{I}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{J}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{K}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{L}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{M}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{N}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{O}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{P}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{Q}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{R}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{S}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{T}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{U}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{V}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{A}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{B}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{C}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{D}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{E}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{F}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{G}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{H}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{I}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{J}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{K}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{L}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{M}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{N}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{A}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{B}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{C}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{D}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{E}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{F}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{G}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{H}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{I}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{J}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{K}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{L}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{M}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{N}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{O}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{P}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{Q}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{A}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{B}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{C}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{D}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{E}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{F}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{G}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{H}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{I}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{J}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{K}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{A}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{B}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{C}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{A}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{B}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{C}");Thread.Sleep(25);
    Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{D}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{E}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{F}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{G}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{H}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{I}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{J}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{K}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{L}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{M}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{N}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{O}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{P}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Q}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{R}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{S}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{T}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{U}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{V}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{W}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{X}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Y}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Z}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Å}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Ä}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Ö}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{A}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{B}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{C}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{D}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{E}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{F}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{G}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{H}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{I}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{J}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{K}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{L}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{M}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{N}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{O}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{P}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Q}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{R}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{S}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{T}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{U}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{V}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{W}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{X}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Y}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Z}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Å}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Ä}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Ö}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}");Thread.Sleep(25);
    Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{A}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{B}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{C}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{D}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{E}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{F}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{G}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{H}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{I}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{J}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{K}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{L}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{M}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{N}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{O}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{P}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{Q}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{R}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{S}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{T}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{U}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{V}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{W}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{X}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{Y}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{Z}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{Å}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{Ä}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{Ö}");Thread.Sleep(25);
Console.Clear();
Console.WriteLine($"{H}{E}{L}{L}{O}{Mellanrum}{W}{O}{R}{L}{D}{Utropstäcken}{Utropstäcken}{Utropstäcken}");Thread.Sleep(25);
Console.Clear();
    Console.ReadLine();
}
Console.ReadLine();